- name: copy script
  copy:
    src: ../scripts/master.sh
    dest: /home/ubuntu
    owner: ubuntu
    mode: 0777
- name: Install k3s
  command: sh /home/ubuntu/master.sh
- name: Fetch the node Token
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: node-token
    flat: yes
     
