- name: Copying the script to the workers
  copy:
   src: ../scripts/worker.sh
   dest: /home/ubuntu
   owner: ubuntu
   mode: 0755
- name: Copying the Node Token from master
  copy:
   src: ./node-token
   dest: /home/ubuntu/
   owner: ubuntu
   mode: 0444
- name: Running the script
  shell: bash /home/ubuntu/worker.sh
